import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// Components
import Header from '@/components/header'
import Footer from '@/components/footer'
// Theme Provider
import { ThemeProvider } from '@/components/themeprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
        <Header />
        {children}
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
